import numpy as np
import matplotlib.pyplot as plt
"""
Auxiliary plotting script to consider better simulated single Bragg
Edge imaging data sets for traning danoising ANN models.
--------------------------------------------------------------------
This script visualizes the valid region in the (alpha, Te) parameter space
when a0_min is negative (e.g., -0.03 to 0.07).

Key Logic:
    Since a0 can be negative, the mathematical expression for Te could
    exceed 1.0. However, transmission is physically capped at 1.0 (100%).
    This creates a horizontal boundary at Te=1.0, resulting in a
    PENTAGONAL shape defined by:
    1. Left/Right vertical bounds from b0_min and b0_max.
    2. Lower curved bound from a0_max.
    3. Upper curved bound from a0_min.
    4. Horizontal 'Ceiling' at Te=1.0 (Physical Clipping).

Use Case:
    Use this script to analyze cases where the experimental baseline (a0)
    might fluctuate around zero, requiring physical thresholding.

First generated by Gemini 3.1 Pro Preview on AI studio.
Adding memo by Kazuyoshi TATSUMI, 2026/05/24
'Defining the physical boundaries for valid transmission modeling.'
"""

# 定数の設定
ti = 23000
te = 26020
C = te - ti
k = te / C

# a0, b0 の範囲
a0_min, a0_max = -0.03, 0.07
b0_min, b0_max = 0.0, 0.1

# alphaの範囲 (b0の条件)
# b0 = 10000 * ln(alpha) / C  =>  ln(alpha) = b0 * C / 10000
alpha_min = np.exp(b0_min * C / 10000)
alpha_max = np.exp(b0_max * C / 10000)

# 境界関数の定義 (a0の条件)
def te_lower(a):
    # a0 = a0_max のとき
    return np.exp(-k * np.log(a) - a0_max)

def te_upper_curve(a):
    # a0 = a0_min のとき
    return np.exp(-k * np.log(a) - a0_min)

# 交点の計算
# 1. 左下 (alpha_min, te_lower)
p1 = (alpha_min, te_lower(alpha_min))

# 2. 右下 (alpha_max, te_lower)
p2 = (alpha_max, te_lower(alpha_max))

# 3. 右上 (alpha_max, te_upper_curve)
# ただし Te <= 1.0 か確認する
p3_te = te_upper_curve(alpha_max)
p3 = (alpha_max, min(1.0, p3_te))

# 4. 上側の曲線が Te=1 と交わる点
# 1 = exp(-k*ln(a) - a0_min) => ln(a) = -a0_min/k
alpha_cut = np.exp(-a0_min / k)
p4 = (alpha_cut, 1.0)

# 5. 左上 (alpha_min, Te=1.0)
p5 = (alpha_min, 1.0)

# グラフ描画用のデータ生成
a_vals = np.linspace(alpha_min, alpha_max, 500)
upper_vals = np.minimum(1.0, te_upper_curve(a_vals))
lower_vals = te_lower(a_vals)

plt.figure(figsize=(10, 7))

# 領域の塗りつぶし
plt.fill_between(a_vals, lower_vals, upper_vals, color='lightgreen', alpha=0.6, label='Valid Region')

# 境界線のプロット
plt.plot(a_vals, lower_vals, 'r-', linewidth=1.5, label=f'$a_0 = {a0_max}$ (Lower)')
plt.plot(a_vals, upper_vals, 'b-', linewidth=1.5, label=f'$a_0 = {a0_min}$ (Upper, clipped at $T_e=1$)')
plt.axvline(alpha_min, color='green', linestyle='--', alpha=0.5, label=f'$\\alpha$ min ($b_0={b0_min}$)')
plt.axvline(alpha_max, color='orange', linestyle='--', alpha=0.5, label=f'$\\alpha$ max ($b_0={b0_max}$)')

# 頂点のプロットと座標表示
vertices = [p1, p2, p3, p4, p5]
for i, (ax, ay) in enumerate(vertices):
    plt.plot(ax, ay, 'ko')
    # テキストの位置を少しずらして見やすくする
    offset_y = 0.01 if ay < 0.9 else -0.015
    plt.text(ax, ay + offset_y, f'({ax:.4f}, {ay:.4f})', fontsize=10, ha='center')

# グラフの設定
plt.title(f'Valid Region of ($\\alpha, T_e$)\n$t_i={ti}, t_e={te}$', fontsize=14)
plt.xlabel('$\\alpha = T_{iext} / T_e$', fontsize=12)
plt.ylabel('$T_e$', fontsize=12)

# 表示範囲の調整（領域が見やすいようにズーム）
plt.xlim(0.998, alpha_max + 0.005)
plt.ylim(0.65, 1.05)

plt.grid(True, which='both', linestyle=':', alpha=0.6)
plt.legend(loc='lower left')

plt.tight_layout()
plt.show()

# 数値データのコンソール出力
print(f"頂点座標 (alpha, Te):")
for i, p in enumerate(vertices, 1):
    print(f"P{i}: ({p[0]:.5f}, {p[1]:.5f})")
