import numpy as np
import matplotlib.pyplot as plt
"""
An auxiliary plotting script to consider better simulated single Bragg
Edge imaging data sets for traning danoising ANN models with a modified
parameters region.
----------------------------------------------------------------------
This script visualizes the valid region in the (alpha, Te) parameter space
when a0 is strictly non-negative (e.g., 0.0 to 0.05).

Key Logic:
    Because a0_min >= 0, the transmission Te is naturally <= 1.0 at alpha=1.
    Therefore, no horizontal clipping at Te=1.0 is required. The region is
    enclosed by four boundaries, forming a CURVED QUADRANGLE (Trapezoid-like):
    1. Left/Right vertical bounds (alpha_min, alpha_max) derived from b0.
    2. Lower curved bound derived from a0_max.
    3. Upper curved bound derived from a0_min.

Use Case:
    Optimized for clean experimental data where a0 (absorptivity offset)
    is always positive, ensuring a simpler geometric sampling space.

First generated by Gemini 3.1 Pro Preview on AI studio.
Adding memo by Kazuyoshi TATSUMI, 2026/05/24
'Implementing a streamlined trapezoidal model for stable parameter sampling.'
"""

# 定数の設定
ti = 23000
te = 26020
C = te - ti
k = te / C

# 指定された範囲
a0_min, a0_max = 0.0, 0.05
b0_min, b0_max = 0.0, 0.1

# alphaの範囲
alpha_min = np.exp(b0_min * C / 10000)
alpha_max = np.exp(b0_max * C / 10000)

# 境界関数の定義
def te_lower(a):
    return np.exp(-k * np.log(a) - a0_max)

def te_upper_curve(a):
    return np.exp(-k * np.log(a) - a0_min)

# ==========================================
# 頂点（交点）の判定
# ==========================================
vertices = []

# 1. 左下
vertices.append((alpha_min, te_lower(alpha_min)))

# 2. 右下
vertices.append((alpha_max, te_lower(alpha_max)))

# 3. 右上 (Te=1.0でクリップ)
p3_te = min(1.0, te_upper_curve(alpha_max))
vertices.append((alpha_max, p3_te))

# 4. 上側の曲線が Te=1.0 と交わるかチェック
# 交点 alpha_cut を計算: 1.0 = exp(-k*ln(a) - a0_min)
alpha_cut = np.exp(-a0_min / k)

# 交点が alpha_min と alpha_max の間に「厳密に」あれば追加
# (今回は alpha_cut = 1.0 となり、alpha_min と重なるため追加されません)
if alpha_min < alpha_cut < alpha_max:
    vertices.append((alpha_cut, 1.0))

# 5. 左上 (Te=1.0でクリップ)
p5_te = min(1.0, te_upper_curve(alpha_min))
vertices.append((alpha_min, p5_te))

# ==========================================
# グラフ描画
# ==========================================
a_vals = np.linspace(alpha_min, alpha_max, 500)
upper_vals = np.minimum(1.0, te_upper_curve(a_vals))
lower_vals = te_lower(a_vals)

plt.figure(figsize=(10, 7))

# 領域の塗りつぶし
plt.fill_between(a_vals, lower_vals, upper_vals, color='lightgreen', alpha=0.6)

# 境界線のプロット
plt.plot(a_vals, lower_vals, 'r-', linewidth=1.5, label=f'$a_0 = {a0_max}$ (Lower)')
plt.plot(a_vals, upper_vals, 'b-', linewidth=1.5, label=f'$a_0 = {a0_min}$ (Upper)')
plt.axhline(1.0, color='gray', linestyle='--', alpha=0.5, label='$T_e = 1.0$ Limit')

# 頂点のプロット
for i, (ax, ay) in enumerate(vertices):
    plt.plot(ax, ay, 'ko')
    # 点が重ならないようにテキスト位置を調整
    offset_y = 0.005 if ay < 0.95 else -0.01
    plt.text(ax, ay + offset_y, f'({ax:.4f}, {ay:.4f})', fontsize=10, ha='center')

# グラフの設定
plt.title(f'Valid Region of ($\\alpha, T_e$)\n$a_0 \in [{a0_min}, {a0_max}], b_0 \in [{b0_min}, {b0_max}]$', fontsize=14)
plt.xlabel('$\\alpha = T_{iext} / T_e$', fontsize=12)
plt.ylabel('$T_e$', fontsize=12)

# 描画範囲の最適化
plt.xlim(alpha_min - 0.005, alpha_max + 0.005)
min_te = min(lower_vals)
plt.ylim(max(0, min_te - 0.03), 1.03)

plt.grid(True, which='both', linestyle=':', alpha=0.6)
plt.legend(loc='lower left')

plt.tight_layout()
plt.show()

# コンソール出力
print("【領域の頂点座標 (alpha, Te)】")
for i, p in enumerate(vertices, 1):
    print(f"頂点{i}: ({p[0]:.5f}, {p[1]:.5f})")
