#!/usr/bin/env python
"""
Calculate eigenvalues and eigenvectors of hydrogen nucleus quantum states
in a crystal within a single particle picture under an adiabatic potential.
- Main parts in the original change_h_pos_in_poscar_class.py are rearranged
  to be like the parts in pypolymlp codes.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Dict, Any, Iterable, Tuple, Optional, Union, Sequence

from pypolymlp.core.data_format import PolymlpStructure
from pypolymlp.api.pypolymlp_calc import PypolymlpCalc
from pathlib import Path
import copy
import numpy as np
import spglib
from scipy.sparse.linalg import LinearOperator, eigsh
from scipy.linalg import eigh
from collections import Counter, defaultdict
from itertools import permutations
from scipy.optimize import minimize, Bounds
# convergence exception
from scipy.sparse.linalg._eigen.arpack.arpack import (
    ArpackNoConvergence,
)

# ------------------------------ Physical constants --------------------------
A0: float = 0.5291772  # Bohr [Å]
EH: float = 27.211  # 1 Hartree [eV]
MH_H: float = 1836.0  # proton mass [me]


# ------------------------------ Data container ------------------------------
@dataclass(frozen=True)
class Structure:
    """Lightweight container for a crystal structure.

    axis : (3,3) Å
    positions : (N,3) fractional
    types : list[int] (len=N)  # per-atom species index, [0, 0, 0, 1, 1, 1]
    n_atoms : list[int] (len=T) # [3, 3]
    elements : list[str] (len=T)  # ['Pd', 'Pd', 'Pd', 'H', 'H', 'H']
    """
    axis: np.ndarray
    positions: np.ndarray
    types: List[int]
    n_atoms: List[int]
    elements: List[str]
    name: str
    comment: str
    volume: float
    # Utility used just before put structure to pypolymlp, as
    # replace of function generate_PolymlpStructure_from_Structure

    def to_pypolymlp(self) -> Dict[str, Any]:
        pos_frac_T = self.positions.T  # (3,N) view（コピー不要）
        return PolymlpStructure(
                axis=np.asarray(self.axis, float),
                positions=pos_frac_T,                 # (3,N)
                n_atoms=list(self.n_atoms),
                types=list(self.types),
                elements=list(self.elements),
                name=self.name,
                comment=self.comment,
                volume=self.volume,
        )


# ------------------------------ POSCAR I/O ------------------------------
class PoscarReader:
    """Read POSCAR/CONTCAR and return a normalized :class:`Structure`.

    The returned positions are fractional.
    """

    def read(self, path: str) -> Tuple[Structure, dict]:
        with open(path, "r", encoding="utf-8") as f:
            lines = f.readlines()
        scale = float(lines[1].split()[0])
        lat = (
            np.array(
                [list(map(float, lines[2 + i].split()[:3])) for i in range(3)]
            )
            * scale
        )
        lines[1] = "   1.00000000000000\n"
        elements_by_types = lines[5].split()
        n_atoms = list(map(int, lines[6].split()))
        elements = [e for i, e in enumerate(elements_by_types)
                    for _ in range(n_atoms[i])]
        types = [i for i, c in enumerate(n_atoms) for _ in range(c)]
        #if "Di" in lines[7] or "di" in lines[7]:
        #    iniline = 8
        #elif "Sel" in lines[7] or "sel" in lines[7]:
        #    iniline = 9
        #else:
        #    iniline = 8  # default fallback
        if "Sel" in lines[7] or "sel" in lines[7]:
            del lines[7]
        iniline = 8
        pos = np.array(
            [
                list(map(float, lines[iniline + i].split()[:3]))
                for i in range(len(types))
            ]
        )
        volume = float(abs(np.linalg.det(lat)))
        s = Structure(axis=lat, positions=pos, types=types, n_atoms=n_atoms,
                      elements=elements, name=lines[0], volume=volume,
                      comment='generated by test5.py')
        meta = {"lines": lines, "iniline": iniline}
        return s, meta


# ------------------------------ Symmetry ------------------------------
class SymmetryAnalyzer:
    """Thin spglib wrapper to obtain primitive/refined cells and
    operations.
    """

    def __init__(self, prim: bool = True, symprec: float = 1e-5):
        self.prim = prim
        self.symprec = symprec

    def refine(self, s: Structure) -> Tuple[Structure, dict]:
        """Return primitive/refined cell with positions sorted by
        species.
        """
        cell = (s.axis, s.positions, np.asarray(s.types, int))
        if self.prim:
            lat, pos, typ = spglib.find_primitive(cell)
        else:
            lat, pos, typ = spglib.refine_cell(cell)
        idx = np.argsort(typ)

        volume = float(abs(np.linalg.det(lat)))
        s2 = Structure(
            axis=lat, positions=pos[idx], types=typ[idx], n_atoms=s.n_atoms,
            elements=s.elements, comment=s.comment, name=s.name, volume=volume,
        )
        return s2, {"sorted_index": idx}

    def operations(self, s: Structure) -> Tuple[np.ndarray, np.ndarray]:
        """Return symmetry rotations and translations for the
        structure.
        """
        cell = (s.axis, s.positions, s.types)
        sym = spglib.get_symmetry(cell, symprec=self.symprec)
        return sym["rotations"], sym["translations"]


def strip_target_H(
    s: Structure, center_frac: Iterable[float], tol: float = 1e-5
) -> Structure:
    """Remove the H atom nearest to ``center_frac`` (fractional) from
    ``s``. Selection uses the smallest periodic distance within a
    tolerance.
    """
    #c = np.asarray(center_frac, float)
    #keep = np.sum(((s.positions - c + 0.5) % 1.0 - 0.5)**2, axis=1) >= tol

    #_types = np.asarray(s.types)[keep]
    #_, n_atoms_new = np.unique(_types, return_counts=True)
    #n_atoms_new = n_atoms_new.tolist()
    #types_new = [idx for idx, _nan in enumerate(n_atoms_new)
    #             for _ in range(_nan)]
    #elements_by_types_new = np.as_array(s.elements_by_types)[
    #        np.unique(_types)].tolist()

    c = np.asarray(center_frac, float)
    keep = np.sum(((s.positions - c + 0.5) % 1.0 - 0.5)**2, axis=1) >= tol
    _types = np.asarray(s.types, int)[keep]
    unique_old = np.unique(_types)
    old2new = {old: new for new, old in enumerate(unique_old)}
    types_new = np.fromiter((old2new[t] for t in _types), int)

    elements_new = np.asarray(s.elements)[keep].tolist()

    _, counts = np.unique(types_new, return_counts=True)
    n_atoms_new = counts.astype(int).tolist()

    return Structure(
        axis=s.axis,
        positions=s.positions[keep],
        types=types_new.tolist(),
        n_atoms=n_atoms_new,
        elements=elements_new,
        name=s.name,
        comment=s.comment,
        volume=s.volume,
    )


# ------------------------------ H-grid ------------------------------
def make_hgrid_and_hlat_cube(
    structure: Structure,
    center_frac: Iterable[float],
    edge_len_frac: Union[float, Iterable[float]],
    nx: int,
    *,
    old_style: bool = False,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return a cubic grid around ``center_frac`` in fractional coords.

    Returns points (nx**3, 3) and an effective lattice (3, 3) for the
    cube.
    """
    center_frac = np.asarray(center_frac, float)
    if np.ndim(edge_len_frac) == 0:
        edge_len_frac = np.array([edge_len_frac] * 3, float)
    else:
        edge_len_frac = np.asarray(edge_len_frac, float)
    dx = edge_len_frac / (nx - 1) if old_style else edge_len_frac / nx
    pts = []
    for ix in range(nx):
        for iy in range(nx):
            for iz in range(nx):
                base = center_frac - edge_len_frac / 2
                p = base + np.array([ix, iy, iz]) * dx
                pts.append(p % 1.0)
    lat = np.asarray(structure.axis, float)
    hlat = lat @ np.diag(edge_len_frac)
    return np.asarray(pts), hlat


# --------------------------- Irreducible representatives ---------------------
def get_irreducible_points(
    hpos: np.ndarray,
    rotations: np.ndarray,
    translations: np.ndarray,
    tol: float = 1e-5,
) -> np.ndarray:
    """Remove symmetry-equivalent grid points and return irreducible
    ones.

    Algorithm
    ---------
    - Apply each non-identity symmetry operation to the current set.
    - Drop points that become identical under that operation (with PBC).
    - Always keep the self-point at each step.
    """
    irr_hpos = np.array(hpos)
    for rot, trans in zip(rotations[1:], translations[1:]):
        sym_hpos = ((np.matmul(rot, irr_hpos.T)).T + trans) % 1.0
        sym_hpos[np.abs(sym_hpos - 1.0) <= 1.0e-14] = 0.0
        cond = np.ones((irr_hpos.shape[0]), dtype=bool)
        for i, _irr in enumerate(irr_hpos):
            if cond[i]:
                diff = np.sum(np.abs(_irr - sym_hpos) % 1.0, axis=1)
                cond *= diff >= tol
                cond[i] = True
        irr_hpos = irr_hpos[cond]
    return irr_hpos


def get_mapping(
    hpos: np.ndarray,
    irr_hpos: np.ndarray,
    rotations: np.ndarray,
    translations: np.ndarray,
    tol: float = 1e-5,
) -> np.ndarray:
    """Map each full-grid point to the index of its irreducible repr."""
    test = (
        np.matmul(rotations, irr_hpos.T).transpose(2, 0, 1) + translations
    ) % 1.0
    test[np.abs(test - 1.0) <= 1.0e-15] = 0.0
    test2 = np.repeat(np.expand_dims(test, 2), hpos.shape[0], axis=2)
    cond = np.prod(
        # np.sum(np.abs(hpos - test2) % 1.0, axis=3) >= tol,
        np.sum(((hpos - test2 + 0.5) % 1.0 - 0.5)**2, axis=3) >= tol,
        axis=1,
        dtype=bool,
    )
    pairs = np.where(np.invert(cond))
    irr_idx = pairs[0][np.argsort(pairs[1])]
    return irr_idx


# ------------------------------ H-index helper ------------------------------
def get_hindex(st: Structure, center_frac) -> int:
    """Return the column index of the target H nearest to center_frac (PBC)."""
    c = np.asarray(center_frac, float)
    dif2 = np.sum(((st.positions - c + 0.5) % 1.0 - 0.5) ** 2, axis=1)
    return int(np.argmin(dif2))


# ----- Write POSCAR files with target H at each irreducible position -----
def generate_shifted_poscar(structure: Structure,
                            irr_hpos: np.ndarray,
                            meta: dict,
                            center_frac) -> None:
    """Write POSCAR_### by replacing the target H (at center_frac, fractional)
    with each irreducible position in `irr_hpos`.
    Only this function is added/modified to minimize diffs.
    """
    lines = list(meta['lines'])
    head = int(meta['iniline'])
    # Update lattice vectors
    lat = np.asarray(structure.axis, float)
    for il in range(3):
        lines[il+2] = "     {:.16f}    {:.16f}    {:.16f} \n"\
                      .format(lat[il, 0], lat[il, 1], lat[il, 2])
        # Overwrite positions and flags (fractional)
    pos = np.asarray(structure.positions, float)
    for il in range(pos.shape[0]):
        lines[head+il] = "  {:.16f}  {:.16f}  {:.16f} \n"\
                         .format(pos[il, 0], pos[il, 1], pos[il, 2])
        # locate target H index
    c = np.asarray(center_frac, float)
    #diffs = np.sum(np.abs((pos - c) % 1.0), axis=1)
    #hits = np.where(diffs < 1e-5)[0]
    diffs = np.sum(((pos - c + 0.5) % 1.0 - 0.5)**2, axis=1)
    hits = np.where(diffs < 1e-10)[0]
    h_idx = int(hits[0]) if hits.size > 0 else int(np.argmin(diffs))
    # filename width
    nd = int(irr_hpos.shape[0])
    width = 5 if nd > 9999 else (4 if nd > 999 else 3)
    for iridx, ir in enumerate(irr_hpos):
        out_lines = lines.copy()
        out_lines[head+h_idx] = "  {:.16f}  {:.16f}  {:.16f} \n"\
                                .format(ir[0], ir[1], ir[2])
        outfile = 'POSCAR_{}'.format(str(iridx+1).zfill(width))
        with open(outfile, 'w') as f:
            f.writelines(out_lines)
    return None


# ------------------------ Adiabatic potential data ---------------------------
def load_energies(path: str, *, relax: bool = False) -> np.ndarray:
    """Load ``ENERGIES`` as a 1D float array.

    If ``relax=False`` use col 4 (idx 3); if True use col 5 (idx 4).
    """
    col = 4 if relax else 3
    ene: list[float] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            ene.append(float(line.split()[col]))
    return np.asarray(ene, dtype=float)


def replace_ene_with_flags(
    ene: np.ndarray, short_atom_distance_flags: np.ndarray, delta: float = 10.0
) -> np.ndarray:
    """Replace energies where flag True with mean(non-flagged) + delta."""
    eave = np.average(ene[~short_atom_distance_flags])
    ene[short_atom_distance_flags] = eave + delta
    return ene


def expand_positions_3x3x3(frac_pos: np.ndarray) -> np.ndarray:
    """Expand fractional coords (M, 3) into 27 periodic images."""
    pos = np.asarray(frac_pos, float)
    shifts = np.array(
        [(i, j, k) for i in (-1, 0, 1)
            for j in (-1, 0, 1) for k in (-1, 0, 1)],
        float,
    )
    return shifts[:, None, :] + pos[None, :, :]


def get_min_bond_length(
    h_frac: np.ndarray, axis: np.ndarray, host_frac: np.ndarray
) -> float:
    """Shortest host–H distance [Å] for a candidate H at ``h_frac``."""
    epos = expand_positions_3x3x3(host_frac)
    diff_frac = epos - np.asarray(h_frac, float)
    diff_cart = diff_frac @ np.asarray(axis, float)
    dists = np.linalg.norm(diff_cart, axis=2)
    return float(np.min(dists))


def check_short_atom_distance_flags(
    irr_points: np.ndarray, woH_structure: Structure, threshold: float = 0.3
) -> np.ndarray:
    """Return True where min host–H distance is below ``threshold`` [Å]."""
    axis = woH_structure.axis
    host = woH_structure.positions
    flags = [
        get_min_bond_length(p, axis, host) < threshold
        for p in np.asarray(irr_points, float)
    ]
    return np.asarray(flags, dtype=bool)


def assemble_potential_3d(
    irr_energies: np.ndarray, mapping: np.ndarray, nx: int
) -> np.ndarray:
    """Assemble (nx, nx, nx) potential array from irreducible energies."""
    return np.asarray(irr_energies, float)[mapping].reshape(nx, nx, nx)


# ==== minimal additions for three-way energies backend ====

def invoke_polymlp(polymlp_opts: dict, r_st: Structure,
                   ) -> (PypolymlpCalc, int):
    polymlp = PypolymlpCalc(**polymlp_opts, verbose=True, require_mlp=True)
    polymlp.structures = copy.deepcopy([r_st.to_pypolymlp()])
    return polymlp


# -------- total energies and atomic forces calculation by pypolymlp ----------
def pypolymlp_eval_batch(polymlp_opts: dict, r_st: Structure,
                         irr_pts: np.ndarray,
                         center_frac,
                         ) -> np.ndarray:
    """
    Total energies and atomic forces of the structues with the target H atom
    at the mesh points are calculated by pypolymlp. The structures are stored
    in a list of pypolymlp structure dataclass and their energies are obtained
    at one execution of pypolymlp.
    """
    hidx = get_hindex(r_st, center_frac)
    pypolymlporgstructures = [r_st.to_pypolymlp()]
    polymlp = invoke_polymlp(polymlp_opts, r_st)
    new_structs = []
    for hpos in irr_pts:
        s = copy.deepcopy(polymlp.structures[0])
        s.positions[:, hidx] = hpos
        new_structs.append(s)
    polymlp.structures = new_structs
    eval_out = polymlp.eval()
    energies = np.asarray(eval_out[0])
    forces = np.asarray(eval_out[1])
    polymlp.structures = pypolymlporgstructures
    return energies, forces


def pypolymlp_relax(polymlp_opts: dict, org_st: Structure,
                  hpoints: np.ndarray, center_frac, nx: int) -> np.ndarray:
    """
    TODO: 実装時に pypolymlp + forces + L-BFGS-B を呼ぶ。
    """
    polymlporgstructures = [org_st.to_pypolymlp()]
    polymlp, hidx = invoke_polymlp(polymlp_opts, org_st, center_frac)
    raise NotImplementedError("polymlp_relax is not implemented yet. Provide relax logic.")


def get_energies_from_vasp_or_prepare_its_poscars(
    irr_pts: np.ndarray,
    r_st: Structure,            # refined 構造（r_st）`
    center_frac: tuple[float, float, float],
    energies_path: str = "ENERGIES",
    meta: Optional[dict] = None,      # VASP で POSCAR 出力が必要なときだけ渡す
) -> np.ndarray | None:
    """
    Return:
      np.ndarray(shape=(N_irrep,))  … energy array
      None … VASP initial run (POSCARs are generated and end temporaly）
    """
    p = Path(energies_path)
    if p.exists():
        return load_energies(str(p))
    if meta is None:
        raise ValueError("VASP ルートで POSCAR を出すには meta が必要です。")
    generate_shifted_poscar(r_st, irr_pts, meta, center_frac)
    print("[INFO] POSCAR_### を生成。VASP 実行後に同じコマンドで再実行してください。")
    return None


def get_energies_from_pypolymlp(
    irr_pts: np.ndarray,
    r_st: Structure,            # refined 構造（r_st）`
    center_frac: tuple[float, float, float],
    polymlp_opts: Optional[dict] = None,
) -> np.ndarray | None:
    """
    Return:
      np.ndarray(shape=(N_irrep,))  … energy array
    Total energies of the structues with the target H atom at the mesh points
    are calculated by pypolymlp. The structures are stored in a list of
    pypolymlp structure dataclass and their energies are obtained at one
    execution of pypolymlp.
    """
    hidx = get_hindex(r_st, center_frac)
    pypolymlporgstructures = [r_st.to_pypolymlp()]
    polymlp = invoke_polymlp(polymlp_opts, r_st)
    new_structs = []
    for hpos in irr_pts:
        s = copy.deepcopy(polymlp.structures[0])
        s.positions[:, hidx] = hpos
        new_structs.append(s)
    polymlp.structures = new_structs
    eval_out = polymlp.eval()
    energies = np.asarray(eval_out[0])
    #forces = np.asarray(eval_out[1])
    polymlp.structures = pypolymlporgstructures
    return energies


def get_energies(
    backend: str,
    *,
    irr_pts: np.ndarray,
    hpoints: np.ndarray,
    r_st: Structure,            # refined 構造（r_st）`
    org_st: Structure,
    center_frac: tuple[float, float, float],
    nx: int,
    energies_path: str = "ENERGIES",
    polymlp_opts: Optional[dict] = None,
    meta: Optional[dict] = None,      # VASP で POSCAR 出力が必要なときだけ渡す
) -> np.ndarray | None:
    """
    Return:
      np.ndarray(shape=(N_irrep,))  … energy array
      None … VASP initial run (POSCARs are generated and end temporaly）
    """
    if backend == "vasp":
        p = Path(energies_path)
        if p.exists():
            return load_energies(str(p))
        if meta is None:
            raise ValueError("VASP ルートで POSCAR を出すには meta が必要です。")
        generate_shifted_poscar(r_st, irr_pts, meta, center_frac)
        print("[INFO] POSCAR_### を生成。VASP 実行後に同じコマンドで再実行してください。")
        return None

    if backend == "pypolymlp-batch":
        return pypolymlp_eval_batch(polymlp_opts, r_st, irr_pts, center_frac)[0]

    if backend == "pypolymlp-relax":
        # TODO: pypolymlp+forces の緩和実装を後で差し込み
        return pypolymlp_relax(polymlp_opts or {}, org_st, hpoints, nx)

    raise ValueError("backend must be 'polymlp-batch' | 'polymlp-relax' | 'vasp'")


# ----------------------------- G-space utilities -----------------------------
def cut_Gs_physically(lattice: np.ndarray, nx: int, ao: float = A0
                      ) -> np.ndarray:
    """Generate G-vectors by a physical cutoff in reciprocal space."""
    A = np.asarray(lattice, float) / A0
    BinvT = np.linalg.inv(A).T
    nnyq = (nx - 1) // 2 - 1
    dist = []
    for axis in range(3):
        vec = np.zeros(3)
        vec[axis] = 1.0
        dist.append(np.linalg.norm(BinvT @ vec))
    mindist = min(dist)
    r_phys = mindist * nnyq
    Gs = []
    for i in range(-nnyq, nnyq + 1):
        for j in range(-nnyq, nnyq + 1):
            for k in range(-nnyq, nnyq + 1):
                G = BinvT @ np.array([i, j, k])
                if np.linalg.norm(G) < r_phys:
                    Gs.append([i, j, k])
    return np.asarray(Gs, dtype=int)


def kinetic_diag(
    Gs: np.ndarray,
    lattice: np.ndarray,
    mh: float = MH_H,
    *,
    a0: float = A0,
    kvec: Optional[Iterable[float]] = None,
) -> np.ndarray:
    """Return the diagonal kinetic energy in Hartree."""
    A = lattice / a0
    BinvT = np.linalg.inv(A).T
    Gcart = (BinvT @ Gs.T).T
    if kvec is not None:
        kcart = BinvT @ np.asarray(kvec, float)
        Gcart = Gcart + kcart
    return (2 * np.pi) ** 2 * np.sum(Gcart ** 2, axis=1) / (2.0 * mh)


# ----------------------------- V operator (FFT) ------------------------------
def fft_coeff(
    V3d: np.ndarray, *, Eh: float = EH, subtract_mean: bool = True
) -> np.ndarray:
    """Return FFT coefficients of ``V/Eh`` with ``norm='forward'``."""
    arr = (V3d - np.mean(V3d)) / Eh if subtract_mean else (V3d / Eh)
    return np.fft.fftn(arr, norm="forward")


def get_V(Gs: np.ndarray, nx: int, z: np.ndarray) -> np.ndarray:
    """Build the potential matrix ``V`` in the G basis via FFT indexing."""
    gi, gj, gk = Gs[:, 0], Gs[:, 1], Gs[:, 2]
    di = (gi[:, None] - gi[None, :]) % nx
    dj = (gj[:, None] - gj[None, :]) % nx
    dk = (gk[:, None] - gk[None, :]) % nx
    return z[di, dj, dk]


# ------------------------------ Krylov solver ------------------------------
class NQEKrylovSolver:
    """Small utility class to solve ``Hψ`` with a Krylov (``eigsh``)
    method.
    """

    def __init__(
        self,
        Gs: np.ndarray,
        nx: int,
        Kdiag: np.ndarray,
        V3d: np.ndarray,
        *,
        subtract_mean: bool = True,
        Eh: float = EH,
        dtype=np.complex128,
    ) -> None:
        self.nx = int(nx)
        self.dtype = dtype
        gmod = (Gs % nx).astype(int)
        self.gidx = (gmod[:, 0], gmod[:, 1], gmod[:, 2])
        self.Ng = gmod.shape[0]
        if subtract_mean:
            self.V_r = (np.asarray(V3d, float) - float(np.mean(V3d))) / Eh
        else:
            self.V_r = np.asarray(V3d, float) / Eh
        self.Kdiag = np.asarray(Kdiag, dtype=dtype)
        self._X = np.zeros((nx, nx, nx), dtype=dtype)
        self.operator = LinearOperator(
            shape=(self.Ng, self.Ng), matvec=self._matvec, dtype=dtype
        )

    def _matvec(self, x: np.ndarray) -> np.ndarray:
        X = self._X
        X.fill(0.0)
        X[self.gidx] = x.astype(self.dtype, copy=False)
        phi_r = np.fft.ifftn(X)
        Y_r = self.V_r * phi_r
        Y_f = np.fft.fftn(Y_r)
        y = Y_f[self.gidx] + self.Kdiag * x
        return y.astype(self.dtype, copy=False)

    def check_hermitian(self, ntry: int = 3, tol: float = 1.0e-10) -> bool:
        """Quick self-check for Hermitian: <x|Hy> == <Hx|y>."""
        for _ in range(ntry):
            rnd = np.random.randn
            x = (rnd(self.Ng) + 1j * rnd(self.Ng)).astype(self.dtype)
            y = (rnd(self.Ng) + 1j * rnd(self.Ng)).astype(self.dtype)
            Hx, Hy = self._matvec(x), self._matvec(y)
            lhs = np.vdot(x, Hy)
            rhs = np.vdot(Hx, y)
            if not np.allclose(lhs, rhs, atol=tol, rtol=0):
                return False
        return True

    def solve(
        self,
        *,
        k: int = 30,
        which: str = "SA",
        tol: float = 1.0e-8,
        maxiter: Optional[int] = None,
        ncv: Optional[int] = None,
        v0: Optional[np.ndarray] = None,
        Eh: float = EH,
        verbose: bool = True,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Compute the lowest ``k`` eigenpairs using ``eigsh``."""
        k_eff = max(1, min(k, self.Ng - 2))
        if ncv is None:
            ncv_eff = min(self.Ng, max(2 * k_eff + 1, 20))
        else:
            ncv_eff = min(self.Ng, max(ncv, k_eff + 1))
        v0_c = None
        if v0 is not None:
            v0_c = np.asarray(v0, dtype=self.dtype)
            if v0_c.shape[0] != self.Ng:
                raise ValueError("v0 length must equal Ng")
        try:
            E_h, U = eigsh(
                self.operator,
                k=k_eff,
                which=which,
                tol=tol,
                maxiter=maxiter,
                ncv=ncv_eff,
                v0=v0_c,
            )
        except ArpackNoConvergence:
            if verbose:
                print("[WARN] eigsh not converge; retry with relaxed tol/ncv")
            ncv_fb = min(self.Ng, max(ncv_eff + max(5, k_eff), 2 * k_eff + 5))
            tol_fb = max(tol, 5e-7)
            E_h, U = eigsh(
                self.operator,
                k=k_eff,
                which=which,
                tol=tol_fb,
                maxiter=maxiter,
                ncv=ncv_fb,
                v0=v0_c,
            )
        idx = np.argsort(E_h.real)
        E_h = E_h[idx].real
        U = U[:, idx]
        E_meV = E_h * Eh * 1000.0
        if verbose:
            msg = "Krylov finished: k={k}, min(E)[meV]={e:.10f}"
            print(msg.format(k=k_eff, e=E_meV[0]))
            print(E_meV[: min(15, E_meV.size)] - E_meV[0])
        return E_meV, U


# ---------------------------- Solvers (Dense path) ---------------------------
def solve_dense_H(
    H: np.ndarray, Compress: bool = False, v: Optional[np.ndarray] = None,
    verbose: bool = True
) -> Tuple[np.ndarray, np.ndarray]:
    """Compute eigenpairs of a dense Hermitian matrix using ``eigh``."""
    if Compress and v is None:
        if verbose:
            print("Compression is used in Eigenvalue solution")
            print("Calculating v matrix of 200 eigen vectors..")
        dummy, v = eigh(H, subset_by_index=[0, 199], driver="evr")
        dummy *= EH * 1000.0
        if verbose:
            print(np.min(dummy))
            print(dummy[0:15] - np.min(dummy))
    if Compress and v is not None:
        if verbose:
            print("Compressing H by v.")
        H_comp = v.conj().T @ H @ v
        if verbose:
            print("Calculating 30 eigen from the compressed H")
            E_comp, U_comp = eigh(H_comp, subset_by_index=[0, 29],
                                  driver="evr")
            E_comp *= EH * 1000.0
        if verbose:
            print(np.min(E_comp))
            print(E_comp[0:15] - np.min(E_comp))
        U = v @ U_comp
        return E_comp, U, v
    if not Compress:
        E, U = eigh(H, subset_by_index=[0, 29])
        E *= EH * 1000.0
        if verbose:
            print("No compression is used in Eigenvalue solution")
            print(np.min(E))
            print(E[0:15] - np.min(E))
        return E, U


# -------------------------- Geometry optimization ----------------------------
@dataclass
class LogCache:
    E: float | None = None
    u: np.ndarray | None = None
    v: np.ndarray | None = None
    g_meV_per_frac: np.ndarray | None = None
    f_meV: float | None = None


def fun(x, case, atomslist, hpoints, nx, hlat, sidx, log: LogCache):
    f = float(get_E0(x, case, atomslist, hpoints, nx, hlat, sidx, log))
    log.f_meV = f
    return f


def jac(x, case, atomslist, hpoints, nx, hlat, sidx, log: LogCache):
    g = get_grad(x, case, atomslist, hpoints, nx, hlat, sidx, log)
    log.g_meV_per_frac = g
    return np.array(g, dtype=float)


def make_callback(log: LogCache):
    k = 0
    conv = 7.8968828318389797

    def cb(xk):
        nonlocal k
        k += 1
        f_meV = log.f_meV
        g_meV_per_frac = log.g_meV_per_frac
        if g_meV_per_frac is None:
            print(f"[cycle {k:3d}] f = {f_meV:.6f} meV, grad = (not computed yet)")
            return
        g_eV_per_Angs = g_meV_per_frac / 1000.0 / conv
        print(f"[cycles {k:3d}] f = {f_meV:.6f} meV",  g_meV_per_frac, "meV/frac", g_eV_per_Angs, "eV/Å")
    return cb


def do_opt(positions, atomslist, case, hpoints, nx, hlat, sidx):
    x0 = positions[atomslist].flatten()
    d_cart = 0.06
    bounds = [(x0[i] - d_cart, x0[i] + d_cart) for i in range(len(x0))]

    log = LogCache()
    cb = make_callback(log)

    res = minimize(
        fun, x0,
        jac=jac,  # jac is almost necessary
        args=(case, atomslist, hpoints, nx, hlat, sidx, log),
        bounds=bounds,
        method="L-BFGS-B",
        callback=cb,
        options={'ftol': 1e-9, 'gtol': 1e-7, 'maxiter': 500},
    )
    print("success:", res.success, "f*:", res.fun, "nit:", res.nit)


def getene_wstr(hpoints, positions, case):
    new_structs = []
    caseorgstructures = copy.deepcopy(case.structures)
    for hpos in hpoints:
        s = copy.deepcopy(case.structures[0])
        s.positions[:, -1] = hpos
        new_structs.append(s)
    case.structures = new_structs
    eval_out = case.eval()
    energies = np.asarray(eval_out[0])
    case.structures = caseorgstructures
    return energies


def get_E0(positions, case, atomslist, hpoints, nx, hlat, sidx, log):
    positions = positions.reshape((-1, 3))
    difmax = np.max(np.abs(positions - case.structures[0].positions[:, atomslist].T))
    if difmax > 1e-15 or log.E == None:
        print('**get_E0: processes from potential to GetEigen are to be done')
        case.structures[0].positions[:, atomslist] = positions.T
        difmax = np.max(np.abs(positions - case.structures[0].positions[:, atomslist].T))
        V3d = getene_wstr(hpoints, positions, case).reshape((nx, nx, nx))
        Gs = cut_Gs_physically(hlat, nx)
        Kdiag = kinetic_diag(Gs, lattice=hlat)
        z = fft_coeff(V3d, subtract_mean=False)
        V = get_V(Gs, nx, z)
        H = np.diag(Kdiag) + V
        E, U, log.v = solve_dense_H(H, Compress=True, v=log.v)
        log.E = E[sidx]
        log.u = U[:, sidx]
        return log.E
    else:
        print('**get_E0: processes from potential to GetEigen are skipped')
    return log.E


def get_grad(positions, case, atomslist, hpoints, nx, hlat, sidx, log):
    fx = []
    positions = positions.reshape((-1, 3))
    difmax = np.max(np.abs(positions - case.structures[0].positions[:, atomslist].T))
    if difmax > 1e-15 or log.E == None:
        print('**get_grad: processeses from potential to GetEigen are to be done')
        case.structures[0].positions[:, atomslist] = positions.T
        V3d = getene_wstr(hpoints, positions, case).reshape((nx, nx, nx))
        Gs = cut_Gs_physically(hlat, nx)
        Kdiag = kinetic_diag(Gs, lattice=hlat)
        z = fft_coeff(V3d, subtract_mean=False)
        V = get_V(Gs, nx, z)
        H = np.diag(Kdiag) + V
        E, U, log.v = solve_dense_H(H, Compress=True, v=log.v)
        log.E = E[sidx]
        log.u = U[:, sidx]
        density = densities_from_states(log.u[:, np.newaxis], [0], Gs, nx)[0]
    else:
        print('**get_grad: processeses from potential to GetEigen are skipped')
        Gs = cut_Gs_physically(hlat, nx)
        density = densities_from_states(log.u[:, np.newaxis], [0], Gs, nx)[0]
    for hpos in hpoints:
        case.structures[0].positions[:, -1] = hpos
        fx.append(case.eval()[1][0][:, atomslist])

    f_meV_per_frac = -np.sum(np.array(fx).T.reshape((-1,) + density.shape) * density, axis=(1,2,3)) / np.sum(density) \
        * 7.8968828318389797 * 1000.0
    return f_meV_per_frac


# -------------------lapper of optimization----------------------------------
def run_opt(
    hpoints: np.ndarray,        # the entire h points
    org_st: Structure,          # orginal structure (org_st)
    nx: int,
    hlat: np.ndarray,
    sidx: int = 0,
    polymlp_opts: Optional[dict] = {'pot': "/home/kazu/WORK/pypolymlp/pd32h1/polymlp.yaml"},
):
    positions = copy.deepcopy(org_st.positions[:-1])
    polymlp = invoke_polymlp(polymlp_opts, org_st)
    atomslist = range(positions.shape[0])
    do_opt(positions, atomslist, polymlp, hpoints, nx, hlat, sidx)


# ------------------------------------ Post -----------------------------------
def _gindex_from_Gs(Gs: np.ndarray, nx: int
                    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Map G vectors to FFT grid indices (same as previous class code)."""
    gmod = (np.asarray(Gs, int) % int(nx)).astype(int)
    return gmod[:, 0], gmod[:, 1], gmod[:, 2]


def densities_from_states(
    U: np.ndarray,
    state_indices: Sequence[int],
    Gs: np.ndarray,
    nx: int,
) -> np.ndarray:
    """
    Return densities |psi_n(r)|^2 for multiple states.
    Assumes U[:, n] is already sorted by ascending energy.

    Returns:
        rho : (n_states, nx, nx, nx)
    """
    gi, gj, gk = _gindex_from_Gs(Gs, nx)

    # Output buffer
    out = np.empty((len(state_indices), nx, nx, nx), dtype=np.float64)

    for i, st in enumerate(state_indices):
        # Fill G-grid
        X = np.zeros((nx, nx, nx), dtype=np.complex128)
        X[gi, gj, gk] = np.asarray(U[:, st], np.complex128, copy=False)

        # FFT → ψ(r)
        psi_r = np.fft.ifftn(X)

        # Density
        out[i] = np.real(psi_r * np.conj(psi_r))

    return out


# =============================
# A-1/A-2/B/C: consistency checks
# =============================
#from typing import Dict, Optional, Tuple

#import numpy as np

try:
    # Optional speed-up for position matching
    from scipy.spatial import cKDTree as KDTree
    _HAS_KDTREE = True
except Exception:  # pragma: no cover
    _HAS_KDTREE = False


def _cell_volume(a_mat: np.ndarray) -> float:
    """Return absolute unit cell volume from a (3, 3) row-lattice matrix."""
    return float(abs(np.linalg.det(a_mat)))


def _orthogonal_procrustes_rows(
    a_rows: np.ndarray,
    b_rows: np.ndarray,
) -> Tuple[np.ndarray, float]:
    """
    Solve min || a_rows @ R - b_rows ||_F  s.t.  R^T R = I, det(R) = +1.
    Returns rotation R (3x3) and Frobenius error.
    """
    u, _, vt = np.linalg.svd(a_rows.T @ b_rows)
    r_mat = u @ vt
    if np.linalg.det(r_mat) < 0.0:
        # Enforce a proper rotation (no inversion)
        u[:, -1] *= -1.0
        r_mat = u @ vt
    err = float(np.linalg.norm(a_rows @ r_mat - b_rows, ord="fro"))
    return r_mat, err


def cells_equivalent_up_to_perm_rot(
    a0: np.ndarray,
    a1: np.ndarray,
    tol: float = 1.0e-8,
) -> Tuple[bool, Optional[Tuple[int, int, int]], Optional[np.ndarray], float]:
    """
    Check if two row-lattice matrices are equivalent up to
    (row) axis permutation and a proper rotation.

    Returns:
        ok: True if equivalent
        perm: best row permutation (tuple of 3) or None
        r_best: best rotation (3x3) or None
        err: Frobenius norm of the best match
    """
    a0 = np.asarray(a0, float)
    a1 = np.asarray(a1, float)

    best_ok = False
    best_perm: Optional[Tuple[int, int, int]] = None
    best_r: Optional[np.ndarray] = None
    best_err = np.inf

    for p in permutations((0, 1, 2)):
        a0p = a0[list(p), :]
        r_mat, err = _orthogonal_procrustes_rows(a0p, a1)
        if err < best_err:
            best_ok = bool(err <= tol)
            best_perm = (int(p[0]), int(p[1]), int(p[2]))
            best_r = r_mat
            best_err = err
        if best_ok:
            break

    return best_ok, best_perm, best_r, float(best_err)


def _pbc_match_cartesian(
    new_cart: np.ndarray,
    old_cart: np.ndarray,
    a_mat: np.ndarray,
    tol_pos: float,
    require_one_to_one: bool,
) -> Tuple[bool, Optional[np.ndarray], str]:
    """
    PBC nearest-neighbor matching in Cartesian space.

    Args:
        new_cart: (N, 3) new Cartesian coordinates.
        old_cart: (N, 3) old Cartesian coordinates.
        a_mat: (3, 3) row-lattice matrix.
        tol_pos: tolerance in Å for nearest distance.
        require_one_to_one: if True, enforce a 1:1 mapping.

    Returns:
        ok, mapping (new_idx -> old_idx), message
    """
    n_atoms = new_cart.shape[0]

    if _HAS_KDTREE:
        shifts = np.array(
            [[i, j, k] for i in (-1, 0, 1)
             for j in (-1, 0, 1) for k in (-1, 0, 1)],
            float,
        )
        images = (old_cart[None, :, :] + shifts[:, None, :] @ a_mat).reshape(
            -1, 3
        )
        tree = KDTree(images)
        dmin, idx = tree.query(new_cart, k=1)
        if np.any(dmin > tol_pos):
            msg = (
                f"position mismatch (max d={np.max(dmin):.3e} Å "
                f"> tol {tol_pos:.1e})"
            )
            return False, None, msg
        j_old = (idx % n_atoms).astype(int)
        if require_one_to_one:
            counts = np.bincount(j_old, minlength=n_atoms)
            if np.any(counts > 1):
                return False, None, "non-1:1 mapping (degeneracy)"
        return True, j_old, "ok"

    # Fallback: O(N^2 * 27)
    used = np.zeros(n_atoms, dtype=bool)
    j_old = np.empty(n_atoms, dtype=int)
    for i in range(n_atoms):
        best_j = -1
        best_d = 1.0e9
        for j in range(n_atoms):
            for si in (-1, 0, 1):
                for sj in (-1, 0, 1):
                    for sk in (-1, 0, 1):
                        diff = new_cart[i] - (
                            old_cart[j]
                            + si * a_mat[0]
                            + sj * a_mat[1]
                            + sk * a_mat[2]
                        )
                        dval = float(np.linalg.norm(diff))
                        if dval < best_d:
                            best_d = dval
                            best_j = j
        if best_d > tol_pos:
            msg = (
                f"position mismatch (d={best_d:.3e} Å "
                f"> tol {tol_pos:.1e})"
            )
            return False, None, msg
        if require_one_to_one and used[best_j]:
            return False, None, "non-1:1 mapping (degeneracy)"
        j_old[i] = best_j
        used[best_j] = True
    return True, j_old, "ok(slow)"


def _blockwise_match_by_elements(
    new_frac: np.ndarray,
    old_frac: np.ndarray,
    a_new: np.ndarray,
    elements_new,
    elements_old,
    tol_pos: float,
    require_one_to_one: bool,
) -> Tuple[bool, Optional[np.ndarray], str]:
    """
    Match by element buckets to avoid Pd<->H mis-assignments.
    """
    mapping = np.empty(len(new_frac), dtype=int)
    new_cart = np.asarray(new_frac, float) @ a_new
    old_cart = np.asarray(old_frac, float) @ a_new

    buckets_new: Dict[object, list] = defaultdict(list)
    buckets_old: Dict[object, list] = defaultdict(list)
    for i, elem in enumerate(elements_new):
        buckets_new[elem].append(i)
    for j, elem in enumerate(elements_old):
        buckets_old[elem].append(j)

    for elem in buckets_new.keys():
        idx_new = np.array(buckets_new[elem], dtype=int)
        idx_old = np.array(buckets_old[elem], dtype=int)
        ok, part, msg = _pbc_match_cartesian(
            new_cart[idx_new],
            old_cart[idx_old],
            a_new,
            tol_pos,
            require_one_to_one,
        )
        if not ok:
            return False, None, f"[{elem}] {msg}"
        mapping[idx_new] = idx_old[part]
    return True, mapping, "ok(elements-split)"


def check_structure_consistency_full(  # noqa: D401
    old_st,
    new_st,
    *,
    # ---- A: cell equivalence ----
    tol_vol: float = 1.0e-8,
    tol_permrot: float = 1.0e-8,
    # ---- B: counts / composition ----
    use_elements: bool = True,
    # ---- C: PBC matching ----
    tol_pos: float = 1.0e-4,
    by_elements: bool = True,
    require_one_to_one: bool = True,
) -> Tuple[bool, Dict[str, object]]:
    """
    Check A-1 (volume), A-2 (perm+rotation), B (counts), C (PBC mapping).

    Returns:
        ok: True if all checks passed
        rep: dict with diagnostics:
             'msg', 'vol_ratio', 'perm', 'R', 'permrot_err',
             'map_new_to_old', 'map_old_to_new', 'type_map'
    """
    rep: Dict[str, object] = {
        "vol_ratio": np.nan,
        "perm": None,
        "R": None,
        "permrot_err": np.nan,
        "map_new_to_old": None,
        "map_old_to_new": None,
        "type_map": None,
    }

    a0 = np.asarray(old_st.axis, float)
    a1 = np.asarray(new_st.axis, float)

    # ---- A-1: volume ratio ----
    v0 = _cell_volume(a0)
    v1 = _cell_volume(a1)
    rep["vol_ratio"] = v1 / v0 if v0 != 0.0 else np.inf
    if abs(rep["vol_ratio"] - 1.0) > tol_vol:
        return False, {**rep, "msg": "cell volume changed (primitive/basis?)"}

    # ---- A-2: axis permutation + rotation equivalence ----
    ok_eq, perm, r_best, err = cells_equivalent_up_to_perm_rot(
        a0, a1, tol=tol_permrot
    )
    rep["perm"] = perm
    rep["R"] = r_best
    rep["permrot_err"] = float(err)
    if not ok_eq:
        msg = (
            "cell differs (not equivalent up to axis-permutation + rotation)"
        )
        return False, {**rep, "msg": msg}

    # ---- B: counts / composition ----
    if len(old_st.positions) != len(new_st.positions):
        return False, {**rep, "msg": "number of atoms changed"}
    if use_elements and hasattr(old_st, "elements") and hasattr(
        new_st, "elements"
    ):
        if Counter(old_st.elements) != Counter(new_st.elements):
            return False, {**rep, "msg": "composition differs (elements)"}
    else:
        # Fallback: only total count via types (labels may change)
        if len(old_st.types) != len(new_st.types):
            return False, {**rep, "msg": "type counts mismatch"}

    # ---- C: PBC nearest-neighbor mapping ----
    # Map old fractional into the *new* lattice frame:
    #   f_old_in_new = f_old @ A0 @ inv(A1), then modulo 1
    t_mat = a0 @ np.linalg.inv(a1)
    old_frac_in_new = (np.asarray(old_st.positions, float) @ t_mat) % 1.0
    new_frac = np.asarray(new_st.positions, float)

    if by_elements and hasattr(old_st, "elements") and hasattr(
        new_st, "elements"
    ):
        ok, map_no, msg = _blockwise_match_by_elements(
            new_frac,
            old_frac_in_new,
            a1,
            new_st.elements,
            old_st.elements,
            tol_pos,
            require_one_to_one,
        )
    else:
        ok, map_no, msg = _pbc_match_cartesian(
            new_frac @ a1,
            old_frac_in_new @ a1,
            a1,
            tol_pos,
            require_one_to_one,
        )

    if not ok:
        return False, {**rep, "msg": msg}

    rep["map_new_to_old"] = map_no.astype(int)
    inv = np.empty_like(map_no)
    inv[map_no] = np.arange(len(map_no), dtype=int)
    rep["map_old_to_new"] = inv.astype(int)

    # Optional: majority-vote new_type -> old_type map
    new_types = np.asarray(new_st.types, int)
    old_types = np.asarray(old_st.types, int)
    type_map: Dict[int, int] = {}
    for ntype in np.unique(new_types):
        idx_n = np.where(new_types == ntype)[0]
        olds = old_types[rep["map_new_to_old"][idx_n]]
        vals, counts = np.unique(olds, return_counts=True)
        type_map[int(ntype)] = int(vals[np.argmax(counts)])
    rep["type_map"] = type_map

    return True, {**rep, "msg": "consistent"}


def reorder_like(
    old_st,
    new_st,
    map_old_to_new: np.ndarray,
    type_map: Optional[Dict[int, int]] = None,
):
    """
    Return a copy of new_st reordered to match old_st atom order.
    Optionally remap type labels with type_map (new_type -> old_type).
    """
    idx = np.asarray(map_old_to_new, int)
    pos2 = np.asarray(new_st.positions, float)[idx]
    types2 = np.asarray(new_st.types, int)[idx]
    if type_map is not None:
        # Vectorized dictionary lookup with fallback identity
        def _map_t(t: int) -> int:
            return int(type_map.get(int(t), int(t)))
        types2 = np.vectorize(_map_t)(types2)
    if hasattr(new_st, "elements"):
        elems2 = np.asarray(new_st.elements, object)[idx].tolist()
    else:
        elems2 = []

    return Structure(
        axis=new_st.axis,
        positions=pos2,
        types=types2.tolist(),
        n_atoms=new_st.n_atoms,
        elements=elems2,
        name=new_st.name,
        comment=new_st.comment,
        volume=new_st.volume,
    )


# ---------------------------- CLI entry (original flow preserved) ------------
# vasp single-point
def _main(
    mode: str = "Dense",  # "Dense" or "Krylov"
    infile: str = "CONTCAR",
    energies_path: str = "ENERGIES",
    center_frac: Iterable[float] = (0.5, 0.5, 0.5),
    edge_len_frac: float = 0.64,
    nx: int = 20,
    prim: bool = False,
    symprec: float = 1.0e-5,
    kvec: Optional[Iterable[float]] = None,
    subtract_mean: bool = True,
    mh: float = MH_H,
) -> Tuple[np.ndarray, np.ndarray]:
    """Minimal pipeline: POSCAR → symmetry → H-grid → irreps → eigenpairs.
       Note that thsi assumes total energies of vasp are stored in
       energies_path.
       If no file of the total energies, execute (1), (2), (3), (4), and (4)',
       prepare the file, execute (1), (2), (3), (4), (5), (6) and (7).
    """
    # --------- IMPORTANT: keep exactly as in your original file ----------
    mode = "Dense"  # "Dense" or "Krylov"
    infile = "CONTCAR"
    energies_path: str = "ENERGIES"
    center_frac = (0.5, 0.5, 0.5)
    edge_len_frac = 0.64
    nx = 20
    prim = False
    kvec = None
    # --------------------------------------------------------------------

    # (1) POSCAR → Structure
    org_st, meta = PoscarReader().read(infile)

    # (2) Symmetry (remove one H at center_frac before operations)
    r_st, _ = SymmetryAnalyzer(prim=prim).refine(org_st)
    woH_st = strip_target_H(r_st, np.asarray(center_frac, float))
    Rot, Trans = SymmetryAnalyzer(prim=prim).operations(woH_st)
    # (2)' check whether org_st and r_st are consistent with eath other
    ok_cc, rep = check_structure_consistency_full(
        old_st=org_st,
        new_st=r_st,
        tol_vol=1.0e-8,
        tol_permrot=1.0e-8,
        tol_pos=1.0e-4,
        use_elements=True,
        by_elements=True,
        require_one_to_one=True,
    )
    if not ok_cc:
        raise RuntimeError(f"[cell consistency NG] {rep['msg']}")

    # (3) H-grid (fractional)
    hpoints, hlat = make_hgrid_and_hlat_cube(
        woH_st,
        center_frac=center_frac,
        edge_len_frac=edge_len_frac,
        nx=nx,
    )

    # (4) Irreps and mapping (irr_idx)
    irr_pts = get_irreducible_points(hpoints, Rot, Trans)
    irr_idx = get_mapping(hpoints, irr_pts, Rot, Trans)

    # (5) Potential reconstruction from irreducible energies
    ene = get_energies_from_vasp_or_prepare_its_poscars(
        irr_pts=irr_pts,
        r_st=r_st,
        center_frac=center_frac,
        energies_path=energies_path,
        meta=meta                         # Only for outputtin VASP POSCAR
    )

    if ene is None:
        return None, None  # ここで一旦終了（VASP を回してから同じコマンドを再実行）

    short_atom_distance_flags = check_short_atom_distance_flags(
        irr_pts, woH_st
    )
    if short_atom_distance_flags.any():
        ene = replace_ene_with_flags(ene, short_atom_distance_flags)
    V3d = assemble_potential_3d(ene, irr_idx, nx)

    # (6) G set, kinetic, and V operator
    Gs = cut_Gs_physically(hlat, nx)
    Kdiag = kinetic_diag(Gs, lattice=hlat, kvec=kvec)
    z = fft_coeff(V3d)

    # (7) Dense eigen-solve / Krylov eigen-solve (original branching)
    if mode == "Dense":
        V = get_V(Gs, nx, z)
        H = np.diag(Kdiag) + V
        E, U = solve_dense_H(H)
    elif mode == "Krylov":
        solver = NQEKrylovSolver(Gs, nx, Kdiag, V3d, subtract_mean=True)
        E, U = solver.solve(k=30, tol=1.0e-8)
    else:
        raise ValueError("mode must be 'Dense' or 'Krylov'")
    return E, U


# pypolymlp-singlepoint
def __main(
    mode: str = "Dense",  # "Dense" or "Krylov"
    infile: str = "CONTCAR",
    center_frac: Iterable[float] = (0.5, 0.5, 0.5),
    edge_len_frac: float = 0.64,
    nx: int = 20,
    prim: bool = False,
    symprec: float = 1.0e-5,
    kvec: Optional[Iterable[float]] = None,
    subtract_mean: bool = True,
    mh: float = MH_H,
) -> Tuple[np.ndarray, np.ndarray]:
    """Minimal pipeline: POSCAR → symmetry → H-grid → irreps → eigenpairs.
       Note that thsi assumes total energies of vasp are stored in
       energies_path.
       If no file of the total energies, execute (1), (2), (3), (4), and (4)',
       prepare the file, execute (1), (2), (3), (4), (5), (6) and (7).
    """
    # --------- IMPORTANT: keep exactly as in your original file ----------
    mode = "Dense"  # "Dense" or "Krylov"
    infile = "CONTCAR"
    center_frac = (0.5, 0.5, 0.5)
    edge_len_frac = 0.64
    nx = 20
    prim = False
    kvec = None
    # --------------------------------------------------------------------

    # (1) POSCAR → Structure
    org_st, meta = PoscarReader().read(infile)

    # (2) Symmetry (remove one H at center_frac before operations)
    r_st, _ = SymmetryAnalyzer(prim=prim).refine(org_st)
    woH_st = strip_target_H(r_st, np.asarray(center_frac, float))
    Rot, Trans = SymmetryAnalyzer(prim=prim).operations(woH_st)
    # (2)' check whether org_st and r_st are consistent with eath other
    ok_cc, rep = check_structure_consistency_full(
        old_st=org_st,
        new_st=r_st,
        tol_vol=1.0e-8,
        tol_permrot=1.0e-8,
        tol_pos=1.0e-4,
        use_elements=True,
        by_elements=True,
        require_one_to_one=True,
    )
    if not ok_cc:
        raise RuntimeError(f"[cell consistency NG] {rep['msg']}")

    # (3) H-grid (fractional)
    hpoints, hlat = make_hgrid_and_hlat_cube(
        woH_st,
        center_frac=center_frac,
        edge_len_frac=edge_len_frac,
        nx=nx,
    )

    # (4) Irreps and mapping (irr_idx)
    irr_pts = get_irreducible_points(hpoints, Rot, Trans)
    irr_idx = get_mapping(hpoints, irr_pts, Rot, Trans)

    # (5) Potential reconstruction from irreducible energies
    ene = get_energies_from_pypolymlp(
        irr_pts=irr_pts,
        r_st=r_st,
        center_frac=center_frac,
        polymlp_opts={'pot': "/home/kazu/WORK/pypolymlp/pdh/222/three_lattices/polymlp.yaml"},
    )

    short_atom_distance_flags = check_short_atom_distance_flags(
        irr_pts, woH_st
    )
    if short_atom_distance_flags.any():
        ene = replace_ene_with_flags(ene, short_atom_distance_flags)
    V3d = assemble_potential_3d(ene, irr_idx, nx)

    # (6) G set, kinetic, and V operator
    Gs = cut_Gs_physically(hlat, nx)
    Kdiag = kinetic_diag(Gs, lattice=hlat, kvec=kvec)
    z = fft_coeff(V3d)

    # (7) Dense eigen-solve / Krylov eigen-solve (original branching)
    if mode == "Dense":
        V = get_V(Gs, nx, z)
        H = np.diag(Kdiag) + V
        E, U = solve_dense_H(H)
    elif mode == "Krylov":
        solver = NQEKrylovSolver(Gs, nx, Kdiag, V3d, subtract_mean=True)
        E, U = solver.solve(k=30, tol=1.0e-8)
    else:
        raise ValueError("mode must be 'Dense' or 'Krylov'")
    return E, U


# pypolymlp-geometry-optimization
def main(
    infile: str = "CONTCAR",
    center_frac: Iterable[float] = (0.5, 0.5, 0.5),
    edge_len_frac: float = 0.32,
    nx: int = 20,
    prim: bool = False,
    sidx: int = 0,
    subtract_mean: bool = True,
    mh: float = MH_H,
) -> Tuple[np.ndarray, np.ndarray]:
    # --------- IMPORTANT: keep exactly as in your original file ----------
    infile = "CONTCAR"
    center_frac = (0.5, 0.5, 0.5)
    edge_len_frac = 0.32
    nx = 20
    prim = False
    sidx = 0
    # --------------------------------------------------------------------

    # (1) POSCAR → Structure
    org_st, meta = PoscarReader().read(infile)

    # (2) H-grid (fractional)
    hpoints, hlat = make_hgrid_and_hlat_cube(
        org_st,
        center_frac=center_frac,
        edge_len_frac=edge_len_frac,
        nx=nx,
    )

    # (3) Geometry optimization
    run_opt(
        hpoints=hpoints,
        org_st=org_st,
        nx=nx,
        hlat=hlat,
        sidx=sidx,
        polymlp_opts={'pot': "/home/kazu/WORK/pypolymlp/pd32h1/polymlp.yaml"},
    )


if __name__ == "__main__":  # pragma: no cover
    e, _u = main()
    if e is None:
        print("POSCAR_XXX are generated, otherwise, geometry optimization is done")
    else:
        print("min(E) [meV]:", float(np.min(e)))

